<html>
<head>
<title>Get Contact via Search/Query</title>
</head>
<body>
<b>PHP Code:</b><br>
&lt;?php<br>
<br>
&nbsp;&nbsp;include_once&nbsp;("/var/www/localhost/files/eloqua.inc");<br>
&nbsp;&nbsp;include_once&nbsp;("eloquaRequest.php");<br>
<br>
&nbsp;&nbsp;$login&nbsp;=&nbsp;new&nbsp;EloquaRequest($eloqua_site,&nbsp;$eloqua_userA,&nbsp;$eloqua_pass,&nbsp;"https://login.eloqua.com/id");<br>
&nbsp;&nbsp;$endPointBase&nbsp;=&nbsp;$login->get("");<br>
&nbsp;&nbsp;$endPointURL&nbsp;=&nbsp;$endPointBase->urls->base&nbsp;.&nbsp;"/API/REST/2.0";<br>
&nbsp;&nbsp;print&nbsp;"$endPointURL ";<br>
<br>
&nbsp;&nbsp;$client&nbsp;=&nbsp;new&nbsp;EloquaRequest($eloqua_site,&nbsp;$eloqua_userA,&nbsp;$eloqua_pass,&nbsp;$endPointURL);<br>
&nbsp;&nbsp;$query_data&nbsp;=&nbsp;$client->get("/data/contacts?search=common_fields%3d%27chris*%27&depth=minimal&orderBy=C_EmailAddress%20ASC");<br>
&nbsp;&nbsp;print&nbsp;"Query&nbsp;data&nbsp;response&nbsp;(PHP): ";<br>
&nbsp;&nbsp;print_r&nbsp;($query_data);<br>
&nbsp;&nbsp;print&nbsp;"&lt;br>&lt;br>";<br>
&nbsp;&nbsp;print&nbsp;"Query&nbsp;data&nbsp;response&nbsp;(JSON): ";<br>
&nbsp;&nbsp;print&nbsp;json_encode($query_data);<br>
?&gt;<br>
<br>
<br>
<b>PHP Code output:</b><br>
<?php

  include_once ("/var/www/localhost/files/eloqua.inc");
  include_once ("eloquaRequest.php");

  $login = new EloquaRequest($eloqua_site, $eloqua_userA, $eloqua_pass, "https://login.eloqua.com/id");
  $endPointBase = $login->get("");
  $endPointURL = $endPointBase->urls->base . "/API/REST/2.0";
  print "$endPointURL<br>";

  $client = new EloquaRequest($eloqua_site, $eloqua_userA, $eloqua_pass, $endPointURL);
  $query_data = $client->get("/data/contacts?search=common_fields%3d%27chris*%27&depth=minimal&orderBy=C_EmailAddress%20ASC");
  print "Query data response (PHP):<br>";
  print_r ($query_data);
  print "<br><br>";
  print "Query data response (JSON):<br>";
  print json_encode($query_data);
?>
</body>
</html>
